name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: "1.21.5"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Go ${{ env.GO_VERSION }}.x
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}.x

      - name: Install lint dependencies
        run: make install-lint-deps

      - name: Run golangci-lint
        run: make lint

      - name: Run tests
        run: make test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go ${{ env.GO_VERSION }}.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
