name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21.5
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install lint dependencies
      run: make install-lint-deps

    - name: Run golangci-lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build
